# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('localized_name', models.CharField(max_length=50)),
                ('primary_attr', models.CharField(max_length=10)),
                ('attack_type', models.CharField(max_length=10)),
            ],
        ),
    ]
