# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('localized_name', models.CharField(max_length=50)),
                ('primary_attr', models.CharField(max_length=10)),
                ('attack_type', models.CharField(max_length=10)),
            ],
        ),
    ]
